# core/els_bridge.py
# Synthesus 2.0 - ELS Bridge (Experience-Learning-Synthesis)
# Captures interactions, extracts candidate patterns, and integrates approved ones

from __future__ import annotations

import json
import sqlite3
import uuid
from contextlib import contextmanager
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any, Dict, List, Optional
from datetime import datetime, timezone


# ---------------------------------------------------------------------------
# Data Models
# ---------------------------------------------------------------------------

@dataclass
class Interaction:
    """
    Represents a single interaction between a character and a user.
    
    Attributes:
        id (str): Unique identifier for the interaction.
        character_id (str): Identifier for the character involved.
        user_input (str): The text input provided by the user.
        character_response (str): The response generated by the character.
        outcome_success (bool): Whether the interaction was considered successful.
        timestamp (str): ISO 8601 formatted timestamp of the interaction.
        metadata (Dict[str, Any]): Additional context or metadata.
    """
    id: str
    character_id: str
    user_input: str
    character_response: str
    outcome_success: bool
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class CandidatePattern:
    """
    Represents a pattern derived from an interaction that is a candidate for integration.
    
    Attributes:
        id (str): Unique identifier for the candidate pattern.
        character_id (str): Identifier for the character the pattern belongs to.
        trigger (str): The input text that triggers this pattern.
        response_template (str): The response template for this pattern.
        score (float): A confidence or quality score for the pattern.
        status (str): The current status of the candidate (e.g., 'pending', 'approved').
        source_interaction_id (str, optional): The ID of the interaction this pattern was 
            extracted from.
        created_at (str): ISO 8601 formatted timestamp of when the candidate was created.
    """
    id: str
    character_id: str
    trigger: str
    response_template: str
    score: float = 0.5
    status: str = "pending"   # "pending" | "approved" | "rejected" | "integrated"
    source_interaction_id: Optional[str] = None
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


# ---------------------------------------------------------------------------
# ELSBridge
# ---------------------------------------------------------------------------

class ELSBridge:
    """
    Experience-Learning-Synthesis Bridge.

    Responsibilities:
    - Capture raw interactions to SQLite
    - Score and surface candidate patterns from successful interactions
    - Persist candidates to JSON for human/automated review
    - Integrate approved candidates back into the pattern store
    """

    SCHEMA = """
    CREATE TABLE IF NOT EXISTS interactions (
        id TEXT PRIMARY KEY,
        character_id TEXT NOT NULL,
        user_input TEXT NOT NULL,
        character_response TEXT NOT NULL,
        outcome_success INTEGER NOT NULL,
        timestamp TEXT NOT NULL,
        metadata TEXT DEFAULT '{}'
    );
    CREATE TABLE IF NOT EXISTS candidate_patterns (
        id TEXT PRIMARY KEY,
        character_id TEXT NOT NULL,
        trigger TEXT NOT NULL,
        response_template TEXT NOT NULL,
        score REAL DEFAULT 0.5,
        status TEXT DEFAULT 'pending',
        source_interaction_id TEXT,
        created_at TEXT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_int_character ON interactions(character_id);
    CREATE INDEX IF NOT EXISTS idx_cand_character ON candidate_patterns(character_id);
    CREATE INDEX IF NOT EXISTS idx_cand_status ON candidate_patterns(status);
    """

    def __init__(
        self,
        db_path: str = "data/interactions.db",
        patterns_path: str = "data/candidate_patterns.json",
    ):
        """
        Initializes the ELSBridge with database and pattern storage paths.

        Args:
            db_path (str): Path to the SQLite database for interactions.
            patterns_path (str): Path to the JSON file for candidate patterns.
        """
        self.db_path = Path(db_path)
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self.patterns_path = Path(patterns_path)
        self._init_db()

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    def _init_db(self) -> None:
        """Initializes the SQLite database schema if it doesn't exist."""
        with self._get_conn() as conn:
            conn.executescript(self.SCHEMA)

    @contextmanager
    def _get_conn(self):
        """
        Context manager for obtaining a database connection.

        Yields:
            sqlite3.Connection: A connection to the interactions database.
        """
        conn = sqlite3.connect(self.db_path, check_same_thread=False)
        conn.row_factory = sqlite3.Row
        try:
            yield conn
            conn.commit()
        except Exception:
            conn.rollback()
            raise
        finally:
            conn.close()

    # ------------------------------------------------------------------
    # Capture
    # ------------------------------------------------------------------

    def capture(
        self,
        character_id: str,
        user_input: str,
        character_response: str,
        outcome_success: bool,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Interaction:
        """
        Captures a new interaction and saves it to the database.
        
        If the interaction is successful, a candidate pattern is automatically extracted.

        Args:
            character_id (str): The ID of the character.
            user_input (str): The user's input text.
            character_response (str): The character's response text.
            outcome_success (bool): Whether the interaction was successful.
            metadata (dict, optional): Metadata for the interaction.

        Returns:
            Interaction: The captured interaction object.
        """
        interaction = Interaction(
            id=str(uuid.uuid4()),
            character_id=character_id,
            user_input=user_input,
            character_response=character_response,
            outcome_success=outcome_success,
            metadata=metadata or {},
        )
        with self._get_conn() as conn:
            conn.execute(
                """
                INSERT INTO interactions
                (id, character_id, user_input, character_response,
                 outcome_success, timestamp, metadata)
                VALUES (?,?,?,?,?,?,?)
                """,
                (
                    interaction.id, interaction.character_id,
                    interaction.user_input, interaction.character_response,
                    int(interaction.outcome_success), interaction.timestamp,
                    json.dumps(interaction.metadata),
                ),
            )
        if outcome_success:
            self._extract_candidate(interaction)
        return interaction

    # ------------------------------------------------------------------
    # Candidate extraction
    # ------------------------------------------------------------------

    def _extract_candidate(self, interaction: Interaction) -> None:
        """
        Extracts a candidate pattern from a successful interaction.

        Args:
            interaction (Interaction): The interaction to extract from.
        """
        words = interaction.user_input.lower().split()
        stop = {"the", "a", "an", "is", "it", "of", "in", "to", "and", "or"}
        sig = [w for w in words if w not in stop][:5]
        if len(sig) < 2:
            return
        trigger = " ".join(sig)
        template = interaction.character_response[:250].strip()
        score = 0.5 + (0.1 if interaction.outcome_success else 0.0)

        cid = str(uuid.uuid4())
        now = datetime.now(timezone.utc).isoformat()
        with self._get_conn() as conn:
            conn.execute(
                """
                INSERT INTO candidate_patterns
                (id, character_id, trigger, response_template,
                 score, status, source_interaction_id, created_at)
                VALUES (?,?,?,?,?,?,?,?)
                """,
                (cid, interaction.character_id, trigger, template,
                 score, "pending", interaction.id, now),
            )

        # Also append to JSON file for easy review
        existing: List[Dict] = []
        if self.patterns_path.exists():
            try:
                existing = json.loads(self.patterns_path.read_text())
            except Exception:
                existing = []
        existing.append({
            "id": cid,
            "character_id": interaction.character_id,
            "trigger": trigger,
            "response_template": template,
            "score": score,
            "status": "pending",
            "source_interaction_id": interaction.id,
            "created_at": now,
        })
        self.patterns_path.write_text(json.dumps(existing, indent=2))

    # ------------------------------------------------------------------
    # Review & Integration
    # ------------------------------------------------------------------

    def get_candidates(
        self,
        character_id: str,
        status: str = "pending",
        limit: int = 50,
    ) -> List[Dict[str, Any]]:
        """
        Retrieves candidate patterns from the database based on character and status.

        Args:
            character_id (str): The character ID to filter by.
            status (str): The status of the candidates (default: 'pending').
            limit (int): The maximum number of candidates to return.

        Returns:
            List[Dict[str, Any]]: A list of candidate patterns as dictionaries.
        """
        with self._get_conn() as conn:
            rows = conn.execute(
                "SELECT * FROM candidate_patterns "
                "WHERE character_id=? AND status=? LIMIT ?",
                (character_id, status, limit),
            ).fetchall()
        return [dict(r) for r in rows]

    def integrate_patterns(
        self,
        character_id: str,
        approved: List[Dict[str, Any]],
    ) -> int:
        """Mark approved candidates as integrated and write to patterns JSON."""
        if not approved:
            return 0

        patterns_file = Path("data/patterns.json")
        existing: List[Dict] = []
        if patterns_file.exists():
            try:
                existing = json.loads(patterns_file.read_text())
            except Exception:
                existing = []

        added = 0
        for a in approved:
            existing.append({
                "character_id": character_id,
                "pattern_type": "reasoning",
                "trigger": a["trigger"],
                "response_template": a["response_template"],
                "weight": a.get("score", 0.5),
            })
            added += 1

        patterns_file.write_text(json.dumps(existing, indent=2))

        # Mark as integrated in DB
        ids = [a["id"] for a in approved]
        with self._get_conn() as conn:
            conn.executemany(
                "UPDATE candidate_patterns SET status='integrated' WHERE id=?",
                [(i,) for i in ids],
            )
        return added

    # ------------------------------------------------------------------
    # Stats
    # ------------------------------------------------------------------

    def stats(self, character_id: str) -> Dict[str, Any]:
        """
        Calculates interaction and candidate statistics for a character.

        Args:
            character_id (str): The character ID.

        Returns:
            Dict[str, Any]: A dictionary containing total interactions, 
                success rate, and pending candidates.
        """
        with self._get_conn() as conn:
            total = conn.execute(
                "SELECT COUNT(*) FROM interactions WHERE character_id=?",
                (character_id,),
            ).fetchone()[0]
            success = conn.execute(
                "SELECT COUNT(*) FROM interactions "
                "WHERE character_id=? AND outcome_success=1",
                (character_id,),
            ).fetchone()[0]
            pending = conn.execute(
                "SELECT COUNT(*) FROM candidate_patterns "
                "WHERE character_id=? AND status='pending'",
                (character_id,),
            ).fetchone()[0]
        return {
            "total_interactions": total,
            "success_rate": round(success / total, 3) if total else 0,
            "pending_candidates": pending,
        }
