# core/generation/ngram_model.py
import pickle
from collections import defaultdict
from typing import Dict, List, Tuple, Optional, DefaultDict

class NgramModel:
    """N-gram language model with backoff and smoothing for native text generation."""
    
    def __init__(self, n: int = 3):
        self.n = n
        # counts[context_tuple][next_token] -> count
        self.counts: DefaultDict[Tuple[str, ...], DefaultDict[str, int]] = defaultdict(lambda: defaultdict(int))
        self.context_totals: DefaultDict[Tuple[str, ...], int] = defaultdict(int)
        self.vocab: set[str] = set()

    def train_from_tables(self, frequency_tables: Dict[str, Dict]):
        """Populate the model from frequency tables generated by VocabEngine."""
        # Unigrams (context = empty tuple)
        for token, count in frequency_tables.get("unigrams", {}).items():
            self.vocab.add(token)
            self.counts[()][token] = count
            self.context_totals[()] += count

        # Bigrams (context = 1-tuple)
        for key, count in frequency_tables.get("bigrams", {}).items():
            parts = key.split(" ")
            if len(parts) == 2:
                t1, t2 = parts
                self.counts[(t1,)][t2] = count
                self.context_totals[(t1,)] += count

        # Trigrams (context = 2-tuple)
        for key, count in frequency_tables.get("trigrams", {}).items():
            parts = key.split(" ")
            if len(parts) == 3:
                t1, t2, t3 = parts
                self.counts[(t1, t2)][t3] = count
                self.context_totals[(t1, t2)] += count

    def get_distribution(self, context: List[str]) -> Dict[str, float]:
        """
        Get the next-token probability distribution using backoff strategy.
        Returns a map of token -> probability.
        """
        context_tokens = [t.lower() for t in context]
        
        # 1. Try trigram context (last 2 tokens)
        if len(context_tokens) >= 2:
            ctx = (context_tokens[-2], context_tokens[-1])
            if ctx in self.counts:
                return self._calculate_probabilities(ctx)
        
        # 2. Backoff to bigram context (last 1 token)
        if len(context_tokens) >= 1:
            ctx = (context_tokens[-1],)
            if ctx in self.counts:
                return self._calculate_probabilities(ctx)
                
        # 3. Final fallback to unigram distribution
        return self._calculate_probabilities(())

    def _calculate_probabilities(self, context: Tuple[str, ...]) -> Dict[str, float]:
        """
        Calculate smoothed probabilities for the given context.
        Uses a simplified Laplace (add-delta) smoothing.
        """
        probs = {}
        context_counts = self.counts[context]
        total = self.context_totals[context]
        
        # Delta for smoothing to handle out-of-vocab or rare contexts
        delta = 0.1
        vocab_size = len(self.vocab)
        
        # Normalized denominator
        denominator = total + (vocab_size * delta)
        
        if denominator == 0:
            return {}

        for token, count in context_counts.items():
            probs[token] = (count + delta) / denominator
            
        return probs

    def save(self, path: str):
        """Serialize the model to a pickle file."""
        with open(path, 'wb') as f:
            data = {
                "n": self.n,
                "counts": {k: dict(v) for k, v in self.counts.items()},
                "context_totals": dict(self.context_totals),
                "vocab": list(self.vocab)
            }
            pickle.dump(data, f)

    @classmethod
    def load(cls, path: str):
        """Load a serialized model from a pickle file."""
        with open(path, 'rb') as f:
            data = pickle.load(f)
            model = cls(n=data["n"])
            model.counts = defaultdict(lambda: defaultdict(int))
            for k, v in data["counts"].items():
                model.counts[k] = defaultdict(int, v)
            model.context_totals = defaultdict(int, data["context_totals"])
            model.vocab = set(data["vocab"])
            return model
