# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cluster.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cluster.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcluster.proto\x12\tsynthesus\"\x97\x01\n\x10ParameterRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12?\n\nparameters\x18\x02 \x03(\x0b\x32+.synthesus.ParameterRequest.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"0\n\x0cSyncResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"7\n\rMemoryRequest\x12\x11\n\tshard_key\x18\x01 \x01(\t\x12\x13\n\x0bstart_index\x18\x02 \x01(\x05\"?\n\x0bMemoryShard\x12\x11\n\tshard_key\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0f\n\x07is_last\x18\x03 \x01(\x08\"U\n\nNodeStatus\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\x12\x10\n\x08load_cpu\x18\x03 \x01(\x02\x12\x16\n\x0euptime_seconds\x18\x04 \x01(\x03\"\x11\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\xd0\x01\n\x0e\x43lusterService\x12\x46\n\x0eSyncParameters\x12\x1b.synthesus.ParameterRequest\x1a\x17.synthesus.SyncResponse\x12\x42\n\x0cStreamMemory\x12\x18.synthesus.MemoryRequest\x1a\x16.synthesus.MemoryShard0\x01\x12\x32\n\tHeartbeat\x12\x15.synthesus.NodeStatus\x1a\x0e.synthesus.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cluster_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARAMETERREQUEST_PARAMETERSENTRY']._loaded_options = None
  _globals['_PARAMETERREQUEST_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_PARAMETERREQUEST']._serialized_start=29
  _globals['_PARAMETERREQUEST']._serialized_end=180
  _globals['_PARAMETERREQUEST_PARAMETERSENTRY']._serialized_start=131
  _globals['_PARAMETERREQUEST_PARAMETERSENTRY']._serialized_end=180
  _globals['_SYNCRESPONSE']._serialized_start=182
  _globals['_SYNCRESPONSE']._serialized_end=230
  _globals['_MEMORYREQUEST']._serialized_start=232
  _globals['_MEMORYREQUEST']._serialized_end=287
  _globals['_MEMORYSHARD']._serialized_start=289
  _globals['_MEMORYSHARD']._serialized_end=352
  _globals['_NODESTATUS']._serialized_start=354
  _globals['_NODESTATUS']._serialized_end=439
  _globals['_ACK']._serialized_start=441
  _globals['_ACK']._serialized_end=458
  _globals['_CLUSTERSERVICE']._serialized_start=461
  _globals['_CLUSTERSERVICE']._serialized_end=669
# @@protoc_insertion_point(module_scope)
