# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cluster_pb2 as cluster__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cluster_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClusterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SyncParameters = channel.unary_unary(
                '/synthesus.ClusterService/SyncParameters',
                request_serializer=cluster__pb2.ParameterRequest.SerializeToString,
                response_deserializer=cluster__pb2.SyncResponse.FromString,
                _registered_method=True)
        self.StreamMemory = channel.unary_stream(
                '/synthesus.ClusterService/StreamMemory',
                request_serializer=cluster__pb2.MemoryRequest.SerializeToString,
                response_deserializer=cluster__pb2.MemoryShard.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/synthesus.ClusterService/Heartbeat',
                request_serializer=cluster__pb2.NodeStatus.SerializeToString,
                response_deserializer=cluster__pb2.Ack.FromString,
                _registered_method=True)


class ClusterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SyncParameters(self, request, context):
        """Sync parameters (traits, facts) between nodes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMemory(self, request, context):
        """Stream memory shards for large-scale retrieval
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Send discovery heartbeat and node status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClusterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SyncParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncParameters,
                    request_deserializer=cluster__pb2.ParameterRequest.FromString,
                    response_serializer=cluster__pb2.SyncResponse.SerializeToString,
            ),
            'StreamMemory': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMemory,
                    request_deserializer=cluster__pb2.MemoryRequest.FromString,
                    response_serializer=cluster__pb2.MemoryShard.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=cluster__pb2.NodeStatus.FromString,
                    response_serializer=cluster__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'synthesus.ClusterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('synthesus.ClusterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClusterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SyncParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synthesus.ClusterService/SyncParameters',
            cluster__pb2.ParameterRequest.SerializeToString,
            cluster__pb2.SyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/synthesus.ClusterService/StreamMemory',
            cluster__pb2.MemoryRequest.SerializeToString,
            cluster__pb2.MemoryShard.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synthesus.ClusterService/Heartbeat',
            cluster__pb2.NodeStatus.SerializeToString,
            cluster__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
