"""
CHAL (Cognitive Hardware Abstraction Layer) Interfaces
Defines the core virtual hardware contracts for Synthesus 4.1.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional


class MountType(str, Enum):
    """The type of cognitive mount."""
    ROM = "ROM"                     # Read-only canonical knowledge/corpora
    PARAMETER_DISK = "PARAMETER_DISK" # Mutable configuration/traits
    CACHE_SEED = "CACHE_SEED"       # Pre-warmed retrieval cache
    GROUNDING_CORPUS = "GROUNDING_CORPUS" # Contextual facts/documents
    SOURCE_PROVENANCE = "SOURCE_PROVENANCE" # Manifests and attribution
    WRITEBACK_MEMORY = "WRITEBACK_MEMORY" # Fluid/Crystallized dynamic memory


@dataclass
class TelemetryRecord:
    """Standardized telemetry for a cognitive operation."""
    operation_id: str
    latency_ms: float
    cache_hit: bool
    confidence: float
    source: str
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class Partition:
    """A logically isolated segment of knowledge or memory."""
    partition_id: str
    namespace: str
    is_read_only: bool
    schema_model: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class Mount:
    """A CHAL Mount point mapping a logical partition to physical storage."""
    mount_path: str
    mount_type: MountType
    partition: Partition
    locality: str = "local" # local, cloud, edge
    trust_level: float = 1.0 # 0.0 - 1.0
    latency_profile: str = "fast" # fast, medium, slow
    is_active: bool = True

    def __post_init__(self):
        if self.mount_type == MountType.ROM:
            self.partition.is_read_only = True


@dataclass
class ModuleMessage:
    """A standardized message passed across the CHAL fabric."""
    message_id: str
    sender: str
    receiver: str
    payload: Dict[str, Any]
    trace_id: str
    timestamp: float


@dataclass
class Checkpoint:
    """A deterministic snapshot of the cognitive state at a specific trace point."""
    checkpoint_id: str
    trace_id: str
    fluid_state_hash: str
    active_mounts: List[str]
    timestamp: float


@dataclass
class CognitiveTask:
    """A scheduled unit of cognitive work."""
    task_id: str
    domain: str
    budget_ms: int
    deadline: float
    payload: Dict[str, Any]


@dataclass
class ExecutionPlan:
    """A multi-step plan generated by the scheduler."""
    plan_id: str
    tasks: List[CognitiveTask]
    fallback_strategy: str
