"""
Synthesizer - Cross-Domain Answer Synthesis
"""

from __future__ import annotations

import re
from typing import Optional, List, Dict, Any, Tuple
from collections import defaultdict
from .utils import get_jaccard_similarity

class CrossDomainSynthesizer:
    """
    Merges multi-domain retrieved contexts into a coherent answer.
    """

    def __init__(self, config: Optional[Dict[str, Any]] = None) -> None:
        self.config = config or {}
        self.domain_weights = self.config.get("domain_weights", {
            "character": 1.2,
            "world": 1.1,
            "knowledge": 1.0,
            "code": 1.3
        })
        self.conflict_resolution = self.config.get("conflict_resolution_strategy", "priority")
        self.similarity_threshold = self.config.get("similarity_threshold", 0.6)
        self.max_tokens_per_domain = self.config.get("max_tokens_per_domain", 500)

    def synthesize(
        self,
        domain_contexts: Dict[str, List[str]],
        query: str,
        metadata: Optional[Dict[str, Any]] = None
    ) -> str:
        if not domain_contexts:
            return "Synthesus could not find sufficient information across domains to answer this query."

        # Deduplicate and weight chunks
        all_chunks = []
        for domain, chunks in domain_contexts.items():
            if not chunks: continue
            
            weight = self.domain_weights.get(domain, 1.0)
            for chunk in chunks:
                if not chunk or not chunk.strip(): continue
                all_chunks.append({
                    "text": chunk.strip(), 
                    "domain": domain, 
                    "weight": weight,
                    "length": len(chunk)
                })

        # Production-grade deduplication using Jaccard and length preference
        unique_chunks = []
        # Sort by weight descending so we prioritize higher domain weights during deduplication
        all_chunks.sort(key=lambda x: x["weight"], reverse=True)
        
        for chunk in all_chunks:
            is_dup = False
            for existing in unique_chunks:
                if get_jaccard_similarity(chunk["text"], existing["text"]) > self.similarity_threshold:
                    # If duplicate, we already have the higher weight one (due to sorting)
                    # but maybe we prefer the longer text if weights are equal
                    if chunk["weight"] == existing["weight"] and chunk["length"] > existing["length"]:
                        existing["text"] = chunk["text"]
                    is_dup = True
                    break
            if not is_dup:
                unique_chunks.append(chunk)

        return self._build_formatted_response(query, unique_chunks)

    def _build_formatted_response(self, query: str, chunks: List[Dict[str, Any]]) -> str:
        if not chunks:
            return "No relevant cross-domain information found for the specified query."

        # Header with metadata if available
        sections = [f"# Synthesus Cross-Domain Analysis\n**Query:** {query}\n"]
        
        # Group by domain
        by_domain = defaultdict(list)
        for c in chunks:
            by_domain[c["domain"]].append(c["text"])

        # Sort domains by priority
        sorted_domains = sorted(
            by_domain.keys(), 
            key=lambda d: self.domain_weights.get(d, 1.0), 
            reverse=True
        )

        for domain in sorted_domains:
            texts = by_domain[domain]
            sections.append(f"## {domain.upper()} ({domain.title()})")
            for t in texts:
                # Add bullet points, ensuring no double bullets if text already has them
                clean_t = t.lstrip("- ").strip()
                sections.append(f"- {clean_t}")
            sections.append("")

        sections.append("---\n*Generated by Synthesus Reasoning Layer v2.5 (Production)*")
        return "\n".join(sections)
